version: '3.8'

services:
#  spring-app:
#    image: my-springapp:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    networks:
#      - my-network

  redis:
    image: "redis:latest"
    container_name: "redis_container"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my-network

volumes:
  redis_data: { }
networks:
  my-network:
    driver: bridge